### PR TITLE
Sort, generalize -Failed password- and add now lockout causes

### PR DESCRIPTION
**Pull request by rmx-it**
Hi,
this change tries to fetch all "Failed password" attemts for any user.
Additionally it tries to lock:
- "authentication error for"
- "Did not receive identification string"
- "Postponed keyboard-interactive for invalid user"

### CODE REVIEW

**Comment by fichtner** [comment]
Can you tell me a little bit about your use case, I am especially curious about the ports option introduction. :)

**Comment by rmx-it** [comment]
Hi,

ganz einfach :-)

Mir ist der Prozess in Opnsense aufegfallen und hab' ihn erst einmal  
nicht in /usr/ports gefunden.
Nachdem auf einigen nicht-opnsense Systemen security/sshguard-pf bei  
mir nicht sauber funktioniert
hab' ich sshlockout_pf erst einmal dort getestet und dabei die mit dem  
ersten Patch gestopften Lücken gefundenen.

Da es auf non-opnsense Systemen keinen WebConfigurator gibt :-> Der  
zweite Patch...

BTW: Sollten wir sshlockout_pf nicht in der FreeBSD/ports Repo verwalten?

Gruß
---
Michael

Zitat von Franco Fichtner <notifications@github.com>:

> Can you tell me a little bit about your use case, I am especially  
> curious about the ports option introduction. :)
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/opnsense/ports/pull/12#issuecomment-133022704


Gruß
---
Michael Reifenberger

**Comment by rmx-it** [comment]
Ups,
in english:
I used sshguard_pf on non-opnsense FreeBSD and found some not-detected flaws:
=> Patch 1

non-Opnsense Systems don't have WebConfigurator:
=> Patch 2

**Comment by fichtner** [comment]
Verstanden, Idee ist also "Downstreaming" zu FreeBSD Ports in einer generischen Version?

In dem Fall würde ich vorschlagen: wir legen ein GitHub Repo an für sshlockout_pf und säubern den Code noch mehr? Also ein eigenes Upstream-Repo weg vom Portstree...

**Comment by rmx-it** [comment]
Or I could commit it to the FreeBSD Repo under security/sshlockout_pf

**Comment by fichtner** [comment]
Right, that would be step 2 in my head. I think the utility deserves a little love if we do this. That way other BSDs could profit/contribute as well.

**Comment by rmx-it** [comment]
OK.
I found an additional impovements in main() already...

**Comment by fichtner** [comment]
OK, closing this for now, will set up opnsense/sshlockout_pf on GitHub and then we polish the port in this tree to use the new repo until you feel it's ready for FreeBSD ports and then switch over to security category. Thanks, exciting. :D

**Comment by fichtner** [comment]
https://github.com/opnsense/sshlockout_pf

Pull requests for now, but we can talk about commit rights soon. :)

**Pull request closed without merging**
