### PR TITLE
Add RAW Options, Add config re-read on sigup

### PR DESCRIPTION
**Pull request by marjohn56**
****Copied the below description from my original PR on HRS-BSD. It's long. :)****

In its current form dhcp6c is limited by the number of OPTIONS that can be sent. This means that for certain ISP's it will not work.

The changes here add the ability to add as many options as needed using the RAW parameter.

For example, these are taken from a working system - with minor changes to protect the passwords!

User class "+FSVDSL_livebox.Internet.softathome.Livebox3";
send raw-option 15 00:2b:46:53:56:44:53:4c:5f:6c:69:76:65:62:6f:78:2e:49:6e:74:65:72:6e:65:74:2e:73:6f:66:74:61:74:68:6f:6d:65:2e:6c:69:76:65:62:6f:78:33;

Vendor class "sagem"
send raw-option 16 00:00:04:0e:00:05:73:61:67:65:6d;

Authentication
send raw-option 11 00:00:00:00:00:00:00:00:00:00:00:61:71:81:2d:66:73:71:71:36:41:78;

It can be seen that the option number is the first number after the "send raw-option, entered as a decimal number.

For example, in the User Class, rfc3315 states that for user class, all that is required is the option length - first byte, then the string itself. As the length will be calculated and entered automatically this is set to 0, or in hex 00. The string is then entered, converted to hex bytes as shown below.

+FSVDSL_livebox.Internet.softathome.Livebox3

becomes

00:2b:46:53:56:44:53:4c:5f:6c:69:76:65:62:6f:78:2e:49:6e:74:65:72:6e:65:74:2e:73:6f:66:74:61:74:68:6f:6d:65:2e:6c:69:76:65:62:6f:78:33

Care obviously needs to be taken when creating these parameters and it is for the advanced only, but it does allow any option(s) to be added, and it works!

I have also added a config re-read on sigup, this means there is no need to kill dhcp6c on conf changes anymore.

### CODE REVIEW

**Comment by fichtner** [comment]
Remove the distfile please. :)

It looks ok to pull into ports, but maybe we should use a copy under opnsense/ ... let me think about this first.

**Comment by marjohn56** [comment]
What distfile is that then?

**Comment by fichtner** [comment]
distfiles/hrs-allbsd-wide-dhcpv6-v20080615.2_GH0.tar.gz went along for the ride

**Comment by marjohn56** [comment]
Erm... how the **** did that get there...

Got to go and do some real work now, I'll try and work that bit out later.

**Comment by fichtner** [comment]
No rush, no worries. :)

**Comment by marjohn56** [comment]
Closed in favour of #56

**Pull request closed without merging**
